### PR TITLE
Fix CodeFolding to work better in Bramble, turn on by default to aid readability

### PR DESCRIPTION
**Pull request by humphd**
I want to try enabling CodeFolding by default, to help users make sense of deep-nesting, and be able to expand/collapse big sections of the code.  This also fixes things to look nicer in Bramble with our DarkTheme.

I got the idea for this reading http://jgregorymcverry.com/thirty-days-with-thimble/ where @jgmac1106 writes:
<blockquote>Keeping track of nested tags is probably the biggest headache I see students encounter.</blockquote>

In this screenshot you can get a sense of what it's like, where I've collapsed the `<head>...</head>` block to get it out of the way so I can focus on other parts of the code

screenshot 2015-09-19 15 32 25

### CODE REVIEW

**Comment by gideonthomas** [comment]
r+

**Comment by humphd** [comment]
@jgmac1106, try https://bramble.mofostaging.net now and see what you think of the code folding.  I haven't pushed it to production yet.

cc @hannahkane, @flukeout fyi as well.

**Comment by jgmac1106** [comment]
That is exactly what my students would need. They so often lose track of
what closing tag goes with what opening tags, especially when things get
complicated.

I tried a bung of tags, div, ul The codefolding worked on every as expected
(on divs but not p). I could not fold on sections.

Codefolding also worked sometimes on style sheets. Knowing how CSS naming
conventions work though may be more of a curricular issue. I still don't
know how to  "cascade" my naming convetions.

I am just glad I wrote the question correctly. I wasn't even sure how to
ask what I wanted to ask. I guess you now speak McVerryism

**Comment by humphd** [comment]
NOTE: it will work for `<p>` tags, but it doesn't kick in until the block is multiple lines long (if it's only a line or two, it's not worth collapsing.

**Comment by hannahkane** [comment]
Love this! Very useful.

**Pull request merged**
